-- ===== 10244 SALE_INVOICE_CUST_INFO =====
select A.E_INVOICE_ID,
       A.E_INVOICE_NBR,
       A.ACCT_ID,
       A.ACCT_NBR,
       C.CERT_NBR,
       to_char(A.Invoice_Begin_Date,'DD/MM/YYY') Invoice_Begin_Date,
       to_CHAR(A.Invoice_End_Date,'DD/MM/YYYY') Invoice_End_Date,
       B.CUST_NAME,
       B.Cust_TYPE
 from e_invoice A,
       CUST B,
       CERT C
where A.CUST_ID = B.CUST_ID
AND B.CERT_ID=C.CERT_ID
  and A.E_INVOICE_NBR  = :E_INVOICE_NBR

-- ===== 10245 SALE_INVOICE_MASTER_SUBS_INFO =====
SELECT SUBS_ID, ACC_NBR, SUBS_PLAN_ID, OFFER_NAME,AGREEMENT_SHORT_NAME
FROM (
    SELECT C.SUBS_ID, C.ACC_NBR, E.SUBS_PLAN_ID, F.OFFER_NAME,E.AGREEMENT_SHORT_NAME
    FROM E_INVOICE A
    JOIN CUST B ON A.CUST_ID = B.CUST_ID
    JOIN SUBS C ON A.ACCT_ID = C.ACCT_ID
    JOIN PROD E ON C.SUBS_ID = E.PROD_ID
    JOIN PROD_ATTR_VALUE D ON C.SUBS_ID = D.PROD_ID AND D.VALUE = 'MASTER'
    JOIN ATTR H ON H.ATTR_ID=D.ATTR_ID AND H.ATTR_CODE='EXP_SUBS_CUSTOMERTYPE'
    JOIN OFFER F ON E.SUBS_PLAN_ID = F.OFFER_ID
    WHERE A.E_INVOICE_NBR = :E_INVOICE_NBR

    UNION
    SELECT C.SUBS_ID, C.ACC_NBR, E.SUBS_PLAN_ID, F.OFFER_NAME,E.AGREEMENT_SHORT_NAME
    FROM E_INVOICE A
    JOIN CUST B ON A.CUST_ID = B.CUST_ID
    JOIN SUBS C ON A.ACCT_ID = C.ACCT_ID
    JOIN PROD E ON C.SUBS_ID = E.PROD_ID
    JOIN OFFER F ON E.SUBS_PLAN_ID = F.OFFER_ID
    WHERE A.E_INVOICE_NBR = :E_INVOICE_NBR)
    WHERE  ROWNUM = 1

-- ===== 10246 SALE_INVOICE_CUST_ADDRESS_INFO =====
SELECT A.COUNTRY,
       A.CITY,
       A.ZIP_CODE,
       A.STATE,
       A.REGION,
       A.STREET_NAME,
       A.STREET_NO,
       A.UPDATE_DATE,
       BUILDING_NAME,
       A.EXT_ADDRESS1
  FROM POST_STD_ADDR A, E_INVOICE B
 WHERE A.CUST_ID = B.CUST_ID
   AND B.E_INVOICE_NBR = :E_INVOICE_NBR

-- ===== 10247 SALE_INVOICE_DEPOSIT_INFO =====
SELECT  SUM(A.CHARGE)/10000*-1 AS DEPOSIT FROM DEPOSIT_ITEM A ,EVENT_PAYMENT B, INSTANT_PAYMENT C WHERE 
A.ACCT_ID=B.ACCT_ID
AND A.EVENT_PAYMENT_ID=B.EVENT_PAYMENT_ID
AND C.EVENT_PAYMENT_ID=B.EVENT_PAYMENT_ID
AND C.E_INVOICE_NBR = :E_INVOICE_NBR

-- ===== 10249 SALE_INVOICE_ADVANCE_PAYMENT_INFO =====
SELECT 
SUM(COALESCE(B.CHARGE,0) + COALESCE(T.CHARGE,0))

AS TOTAL_ADVANCE_PAYMENT
  
FROM (
    -- 主费用记录
    SELECT 
        B.DEDUCT_SEQ,
        B.PRICE_ID,
  
        B.CHARGE,
        F.ACCT_ITEM_TYPE_NAME AS FEE_ITEM,
        TO_CHAR(B.State_Date, 'HH:MIam') AS PAYMENT_TIME
    FROM EVENT_CHARGE B , ACCT_ITEM_TYPE F, EVENT_CHARGE_EXT H
    where  F.ACCT_ITEM_TYPE_ID = B.ACCT_ITEM_TYPE_ID
    AND B.BILLING_CYCLE_ID IS NOT NULL
    AND B.E_INVOICE_NBR = :E_INVOICE_NBR
    AND H.EVENT_INST_ID = B.EVENT_INST_ID
    AND H.PRICE_ID = B.PRICE_Id
 
    AND H.SEQ = B.SEQ
    AND H.DEDUCT_SEQ = B.DEDUCT_SEQ
    AND H.IS_TAX IS NULL
    AND F.ACCT_ITEM_TYPE_CODE='PLAN_ADVANCE_PAYMENT'
) B
-- 关联税项记录
left JOIN (
     SELECT 
        B.DEDUCT_SEQ,
        B.PRICE_ID,
        B.CHARGE,
        F.ACCT_ITEM_TYPE_NAME AS FEE_ITEM,
        TO_CHAR(B.State_Date, 'HH:MIam') AS PAYMENT_TIME
    FROM EVENT_CHARGE B , ACCT_ITEM_TYPE F, EVENT_CHARGE_EXT H
    where  F.ACCT_ITEM_TYPE_ID = B.ACCT_ITEM_TYPE_ID
    AND B.BILLING_CYCLE_ID IS NOT NULL
    AND B.E_INVOICE_NBR = :E_INVOICE_NBR
    AND H.EVENT_INST_ID = B.EVENT_INST_ID
    AND H.PRICE_ID = B.PRICE_Id
 
    AND H.SEQ = B.SEQ
    AND H.DEDUCT_SEQ = B.DEDUCT_SEQ
    AND H.IS_TAX='Y'
     
) T ON T.PRICE_ID = B.PRICE_ID 
    AND T.DEDUCT_SEQ <> B.DEDUCT_SEQ

-- ===== 10250 SALE_INVOICE_PAYMENT_SUMMARY_INFO =====
SELECT 
    NVL(MAIN_FEE.TOTAL_AMOUNT, 0) + NVL(DEPOSIT_FEE.DEPOSIT_AMOUNT, 0) AS TOTAL_AMOUNT
FROM 
    (-- 主费用部分
    SELECT SUM(B.CHARGE) AS TOTAL_AMOUNT
    FROM EVENT_CHARGE B
    JOIN ACCT_ITEM_TYPE C ON B.ACCT_ITEM_TYPE_ID = C.ACCT_ITEM_TYPE_ID
    WHERE C.ACCT_ITEM_TYPE_CODE NOT IN ('ZRL','ROUNDING')
      AND B.BILLING_CYCLE_ID IS NOT NULL
      AND B.E_INVOICE_NBR = :E_INVOICE_NBR
    ) MAIN_FEE,
    (-- 押金部分（转换为相同单位）
    SELECT SUM(A.CHARGE)  * -1 AS DEPOSIT_AMOUNT
    FROM DEPOSIT_ITEM A 
    JOIN EVENT_PAYMENT B 
      ON A.ACCT_ID = B.ACCT_ID 
     AND A.EVENT_PAYMENT_ID = B.EVENT_PAYMENT_ID
    JOIN INSTANT_PAYMENT C 
      ON C.EVENT_PAYMENT_ID = B.EVENT_PAYMENT_ID
    WHERE C.E_INVOICE_NBR = :E_INVOICE_NBR
    ) DEPOSIT_FEE

-- ===== 10251 SALE_INVOICE_PAYMENTMETHOD_INFO =====
WITH Target_IDs AS (
    SELECT DISTINCT EVENT_PAYMENT_ID
    FROM INSTANT_PAYMENT
    WHERE E_INVOICE_NBR = :E_INVOICE_NBR
)
SELECT 
    E.EVENT_PAYMENT_ID,
    E.PAYMENT_METHOD_ID,
    PM.PAYMENT_METHOD_NAME,
    E.SUBMIT_AMOUNT AS AMOUNT,
    TO_CHAR(E.CREATED_DATE, 'HH:MIam') AS CREATED_DATE
FROM INSTANT_PAYMENT E
JOIN PAYMENT_METHOD PM ON E.PAYMENT_METHOD_ID = PM.PAYMENT_METHOD_ID
WHERE E.EVENT_PAYMENT_ID IN (SELECT EVENT_PAYMENT_ID FROM Target_IDs)
ORDER BY E.CREATED_DATE

-- ===== 10265 SALE_INVOICE_CHARGE_DETAILS_INFO =====
SELECT
    T.CUST_ORDER_ID,
    T.ACC_NBR,
    T.ACCT_ID,
    T.CHARGE,
    T.DISCOUNT_CHARGE,
    T.DISCOUNT_INFO,
    T.FEE_ITEM,
    T.PAYMENT_TIME,
    T.PAYMENT_DATE,
    T.AGREEMENT_PERIOD,
    T.TAX_CHARGE,
    T.Rounding_amount,
    T.TAX_RATE,
    T.OFFER_NAME,
     CASE
        WHEN T.GOODS_ORDER_ID IS NOT NULL AND
             T.CHARGE = MAX(T.CHARGE) OVER (PARTITION BY T.CUST_ORDER_ID, T.ACC_NBR, T.GOODS_ORDER_ID)
        THEN LISTAGG(DISTINCT T.MODEL_NAME, CHR(10)) WITHIN GROUP (ORDER BY
                 CASE WHEN T.MODEL_NAME LIKE '%Adapter%' THEN 2 ELSE 1 END,
                 T.MODEL_NAME
             ) OVER (PARTITION BY T.CUST_ORDER_ID)
        ELSE NULL
    END AS MODEL_NAME,
    T.GOODS_ORDER_ID
FROM
    (SELECT
        B.CUST_ORDER_ID,
        B.ACC_NBR,
        B.ACCT_ID,
        B.CHARGE AS CHARGE,
        COALESCE(ECD.TOTAL_DISCOUNT, 0) AS DISCOUNT_CHARGE,
        ECD.DISCOUNT_INFO,
        B.FEE_ITEM,
        B.PAYMENT_TIME,
        B.PAYMENT_DATE,
        B.AGREEMENT_PERIOD,
        T.CHARGE AS TAX_CHARGE,
        CASE WHEN ROW_NUMBER() OVER (PARTITION BY B.CUST_ORDER_ID ORDER BY B.DEDUCT_SEQ) = 1
             THEN NVL(R.ROUNDING_AMOUNT, 0)
             ELSE 0
        END AS ROUNDING_AMOUNT,
        B.TAX_RATE,
        B.OFFER_NAME,
        M.GOODS_ORDER_ID,
        M.MODEL_NAME
    FROM (
        -- Main fee records
        SELECT
            D.CUST_ORDER_ID,
            B.DEDUCT_SEQ,
            B.PRICE_ID,
            D.ACC_NBR,
            D.ACCT_ID,
            B.CHARGE,
            B.EVENT_INST_iD,
            F.ACCT_ITEM_TYPE_NAME AS FEE_ITEM,
            TO_CHAR(B.State_Date, 'HH' || ':' || 'MIam') AS PAYMENT_TIME,
            TO_CHAR(B.State_Date, 'DD-Mon-YYYY') AS PAYMENT_DATE,
            CASE
                WHEN M.agreement_period <> 0 THEN
                     TO_CHAR(SA.EFF_DATE, 'DD Mon YYYY') || ' – ' || TO_CHAR(SA.EXP_DATE, 'DD Mon YYYY')
                ELSE
                     NULL
            END AS AGREEMENT_PERIOD,
            G.TAX_RATE,
            AG.AGREEMENT_SHORT_NAME AS OFFER_NAME,
            F.ACCT_ITEM_TYPE_ID,
            F.ACCT_ITEM_TYPE_CODE,
            EP.EVENT_PAYMENT_ID
        FROM RE_CC_INST A, EVENT_CHARGE B, RE_SUBS_ORDER_INST C, CRM.ORDER_ITEM D, ACCT_ITEM_TYPE F, EVENT_CHARGE_EXT H, GST_TYPE_TAX_RATE G, OFFER J, GST_TYPE K,CRM.AGREEMENT_ORDER M,AGREEMENT AG,
        EVENT_PAYMENT EP, SUBS_AGREEMENT_INST SA
        WHERE A.EVENT_INST_ID = B.EVENT_INST_ID
        AND M.SUBS_AGREEMENT_INST_ID=SA.AGREEMENT_INST_ID
        AND A.EVENT_INST_ID = C.EVENT_INST_ID
        AND D.ORDER_ITEM_ID = C.ORDER_ITEM_ID
        AND F.ACCT_ITEM_TYPE_ID = B.ACCT_ITEM_TYPE_ID
        AND B.BILLING_CYCLE_ID IS NOT NULL
        AND B.E_INVOICE_NBR = :E_INVOICE_NBR
        AND H.EVENT_INST_ID = B.EVENT_INST_ID
        AND H.PRICE_ID = B.PRICE_ID
        AND D.SUBS_PLAN_ID = J.OFFER_iD
        AND C.CUST_ORDER_ID = D.CUST_ORDER_ID
        AND H.SEQ = B.SEQ
        AND F.GST_TYPE = K.GST_TYPE
        AND F.GST_TYPE <> 'Z'
        AND H.DEDUCT_SEQ = B.DEDUCT_SEQ
        AND H.IS_TAX IS NULL
        AND F.GST_TYPE = G.GST_TYPE
        AND D.ORDER_ITEM_ID=M.ORDER_ITEM_ID
        AND M.AGREEMENT_ID = AG.AGREEMENT_ID
        AND C.EVENT_PAYMENT_ID=EP.EVENT_PAYMENT_ID
        AND D.SUBS_EVENT_ID=1
    ) B

    LEFT JOIN (
    SELECT 
        EVENT_INST_ID,
        PRICE_ID,
        SUM(DISCOUNT_CHARGE) AS TOTAL_DISCOUNT,
        LISTAGG(VOUCHER_CODE || '(' || TO_CHAR(ROUND(discount_charge / -10000, 4), 'FM999999990.00') || ')', CHR(10))
            WITHIN GROUP (ORDER BY discount_charge DESC) AS DISCOUNT_INFO
    FROM EVENT_CHARGE_DISCOUNT
    GROUP BY EVENT_INST_ID, PRICE_ID
) ECD ON B.EVENT_INST_ID = ECD.EVENT_INST_ID
     AND B.PRICE_ID = ECD.PRICE_ID
    -- Tax records
    LEFT JOIN (
        SELECT
            D.CUST_ORDER_ID,
            B.DEDUCT_SEQ,
            B.PRICE_ID,
            B.CHARGE,
            D.ACC_NBR
        FROM RE_CC_INST A, EVENT_CHARGE B, RE_SUBS_ORDER_INST C, CRM.ORDER_ITEM D, EVENT_CHARGE_EXT H,EVENT_PAYMENT EP
        WHERE A.EVENT_INST_ID = B.EVENT_INST_ID
        AND A.EVENT_INST_ID = C.EVENT_INST_ID
        AND D.ORDER_ITEM_ID = C.ORDER_ITEM_ID
        AND B.BILLING_CYCLE_ID IS NOT NULL
        AND B.E_INVOICE_NBR = :E_INVOICE_NBR
        AND H.EVENT_INST_ID = B.EVENT_INST_ID
        AND H.PRICE_ID = B.PRICE_ID
        AND H.SEQ = B.SEQ
        AND C.EVENT_PAYMENT_ID=EP.EVENT_PAYMENT_ID
        AND C.CUST_ORDER_ID = D.CUST_ORDER_ID
        AND H.DEDUCT_SEQ = B.DEDUCT_SEQ
        AND H.IS_TAX = 'Y'
        AND D.SUBS_EVENT_ID=1
    ) T ON T.PRICE_ID = B.PRICE_ID
        AND T.DEDUCT_SEQ <> B.DEDUCT_SEQ
        AND T.ACC_NBR = B.ACC_NBR
        AND T.CUST_ORDER_ID = B.CUST_ORDER_ID
    -- Rounding amount
    LEFT JOIN (
        SELECT
            D.CUST_ORDER_ID,
            MAX(B.CHARGE) AS ROUNDING_AMOUNT
        FROM RE_CC_INST A, EVENT_CHARGE B, RE_SUBS_ORDER_INST C, CRM.ORDER_ITEM D, ACCT_ITEM_TYPE F
        WHERE A.EVENT_INST_ID = B.EVENT_INST_ID
        AND A.EVENT_INST_ID = C.EVENT_INST_ID
        AND D.ORDER_ITEM_ID = C.ORDER_ITEM_ID
        AND C.CUST_ORDER_ID = D.CUST_ORDER_ID
        AND D.SUBS_EVENT_ID=1
        AND F.ACCT_ITEM_TYPE_ID = B.ACCT_ITEM_TYPE_ID
        AND B.BILLING_CYCLE_ID IS NOT NULL
        AND B.E_INVOICE_NBR = :E_INVOICE_NBR
        AND F.ACCT_ITEM_TYPE_CODE IN ('ROUNDING')
        GROUP BY D.CUST_ORDER_ID
    ) R ON R.CUST_ORDER_ID = B.CUST_ORDER_ID
    LEFT JOIN (
        ---- GOODS Info - 修改品牌拼接逻辑和显示顺序
        SELECT
            CUST_ORDER_ID,
            GOODS_ORDER_ID,
            ACC_NBR,
            MODEL_NAME
        FROM (
            SELECT DISTINCT
                D.CUST_ORDER_ID,
                E.GOODS_ORDER_ID,
                D.ACC_NBR,
                CASE
                    WHEN H.MODEL_NAME LIKE '%Adapter%' THEN
                        CASE WHEN I_ADAPTER.VALUE IS NOT NULL
                             THEN BR.BRAND_NAME || ' ' || H.MODEL_NAME || CHR(10) || I_ADAPTER.VALUE
                             ELSE BR.BRAND_NAME || ' ' || H.MODEL_NAME
                        END
                    ELSE
                        CASE WHEN I_PHONE.VALUE IS NOT NULL
                             THEN BR.BRAND_NAME || ' ' || H.MODEL_NAME || CHR(10) || I_PHONE.VALUE
                             ELSE BR.BRAND_NAME || ' ' || H.MODEL_NAME
                        END
                END AS MODEL_NAME,
                CASE WHEN H.MODEL_NAME LIKE '%Adapter%' THEN 2 ELSE 1 END AS SORT_ORDER
            FROM
                RE_CC_INST A
                JOIN EVENT_CHARGE B ON A.EVENT_INST_ID = B.EVENT_INST_ID
                JOIN RE_SUBS_ORDER_INST C ON A.EVENT_INST_ID = C.EVENT_INST_ID
                JOIN CRM.ORDER_ITEM D ON D.ORDER_ITEM_ID = C.ORDER_ITEM_ID AND D.CUST_ORDER_ID = C.CUST_ORDER_ID
                JOIN ACCT_ITEM_TYPE F ON F.ACCT_ITEM_TYPE_ID = B.ACCT_ITEM_TYPE_ID
                JOIN CRM.GOODS_ORDER E ON D.ORDER_ITEM_ID = E.ORDER_ITEM_ID
                JOIN CRM.GM_MODEL H ON H.MODEL_ID = E.MODEL_ID
                JOIN CRM.GM_BRAND BR ON H.BRAND_ID=BR.BRAND_ID
                AND BR.BRAND_CODE NOT IN ('YES','Others')
                JOIN CRM.AGREEMENT_ORDER M ON D.ORDER_ITEM_ID = M.ORDER_ITEM_ID
                JOIN AGREEMENT AG ON M.AGREEMENT_ID = AG.AGREEMENT_ID
                AND AG.AGREEMENT_TYPE_ID='4'
                LEFT JOIN CRM.GOODS_ORDER_ATTR I_ADAPTER ON E.GOODS_ORDER_ID = I_ADAPTER.GOODS_ORDER_ID
                    AND I_ADAPTER.ATTR_ID = 907129
                    AND H.MODEL_NAME LIKE '%Adapter%'
                LEFT JOIN CRM.GOODS_ORDER_ATTR I_PHONE ON E.GOODS_ORDER_ID = I_PHONE.GOODS_ORDER_ID
                    AND I_PHONE.ATTR_ID = 2725
                    AND H.MODEL_NAME NOT LIKE '%Adapter%'
            WHERE
                B.BILLING_CYCLE_ID IS NOT NULL
                AND B.E_INVOICE_NBR = :E_INVOICE_NBR
                AND D.SUBS_EVENT_ID = 1
        )
    ) M ON M.CUST_ORDER_ID = B.CUST_ORDER_ID AND M.ACC_NBR = B.ACC_NBR

    UNION ALL

    --tax 部分
    SELECT
        P.CUST_ORDER_ID,
        P.ACC_NBR,
        P.ACCT_ID,
        P.CHARGE AS CHARGE,
        COALESCE(ECD.TOTAL_DISCOUNT, 0) AS DISCOUNT_CHARGE,
        ECD.DISCOUNT_INFO,
        P.FEE_ITEM,
        P.PAYMENT_TIME,
        P.PAYMENT_DATE,
        P.AGREEMENT_PERIOD,
        P.TAX_CHARGE AS TAX_CHARGE,
        P.ROUNDING_AMOUNT,
        P.TAX_RATE,
        P.OFFER_NAME,
        M.GOODS_ORDER_ID,
        M.MODEL_NAME
    FROM (
        SELECT
            D.CUST_ORDER_ID,
            D.ACC_NBR,
            D.ACCT_ID,
            B.CHARGE AS CHARGE,
            B.DISCOUNT_CHARGE AS DISCOUNT_CHARGE,
            B.EVENT_INST_ID,
            B.PRICE_ID,
            F.ACCT_ITEM_TYPE_NAME AS FEE_ITEM,
            TO_CHAR(B.State_Date, 'HH' || ':' || 'MIam') AS PAYMENT_TIME,
            TO_CHAR(B.State_Date, 'DD-Mon-YYYY') AS PAYMENT_DATE,
            CASE
                WHEN M.agreement_period <> 0 THEN
                     TO_CHAR(SA.EFF_DATE, 'DD Mon YYYY') || ' – ' || TO_CHAR(SA.EXP_DATE, 'DD Mon YYYY')
                ELSE
                     NULL
            END AS AGREEMENT_PERIOD,
            0 AS TAX_CHARGE,
            0 AS ROUNDING_AMOUNT,
            J.TAX_RATE,
            AG.AGREEMENT_SHORT_NAME AS OFFER_NAME
        FROM RE_CC_INST A, EVENT_CHARGE B, RE_SUBS_ORDER_INST C, CRM.ORDER_ITEM D, ACCT_ITEM_TYPE F,GST_TYPE H,GST_TYPE_TAX_RATE J,OFFER K,CRM.AGREEMENT_ORDER M,AGREEMENT AG,
        SUBS_AGREEMENT_INST SA
        WHERE A.EVENT_INST_ID = B.EVENT_INST_ID
        AND A.EVENT_INST_ID = C.EVENT_INST_ID
        AND M.SUBS_AGREEMENT_INST_ID=SA.AGREEMENT_INST_ID
        AND D.ORDER_ITEM_ID = C.ORDER_ITEM_ID
        AND F.GST_TYPE = H.GST_TYPE
        AND D.SUBS_PLAN_ID=K.OFFER_ID
        AND D.SUBS_EVENT_ID=1
        AND D.CUST_ORDER_ID = C.CUST_ORDER_ID
        AND F.ACCT_ITEM_TYPE_ID = B.ACCT_ITEM_TYPE_ID
        AND B.BILLING_CYCLE_ID IS NOT NULL
        AND B.E_INVOICE_NBR = :E_INVOICE_NBR
        AND H.GST_TYPE = 'Z'
        AND D.ORDER_ITEM_ID=M.ORDER_ITEM_ID
        AND M.AGREEMENT_ID = AG.AGREEMENT_ID
        AND H.GST_TYPE=J.GST_TYPE
        AND F.ACCT_ITEM_TYPE_CODE not in ('ZRL','ROUNDING')
    ) P
    LEFT JOIN (
    SELECT 
        EVENT_INST_ID,
        PRICE_ID,
        SUM(DISCOUNT_CHARGE) AS TOTAL_DISCOUNT,
        LISTAGG(VOUCHER_CODE || '(' || TO_CHAR(ROUND(discount_charge / -10000, 4), 'FM999999990.00') || ')', CHR(10))
            WITHIN GROUP (ORDER BY discount_charge DESC) AS DISCOUNT_INFO
    FROM EVENT_CHARGE_DISCOUNT
    GROUP BY EVENT_INST_ID, PRICE_ID
) ECD ON P.EVENT_INST_ID = ECD.EVENT_INST_ID
     AND P.PRICE_ID = ECD.PRICE_ID
    LEFT JOIN (
        ---- GOODS Info
        SELECT
            CUST_ORDER_ID,
            GOODS_ORDER_ID,
            ACC_NBR,
            MODEL_NAME
        FROM (
            SELECT DISTINCT
                D.CUST_ORDER_ID,
                E.GOODS_ORDER_ID,
                D.ACC_NBR,
                CASE
                    WHEN H.MODEL_NAME LIKE '%Adapter%' THEN
                        CASE WHEN I_ADAPTER.VALUE IS NOT NULL
                             THEN BR.BRAND_NAME || ' ' || H.MODEL_NAME || CHR(10) || I_ADAPTER.VALUE
                             ELSE BR.BRAND_NAME || ' ' || H.MODEL_NAME
                        END
                    ELSE
                       CASE WHEN I_PHONE.VALUE IS NOT NULL
                             THEN BR.BRAND_NAME || ' ' || H.MODEL_NAME || CHR(10) || I_PHONE.VALUE
                             ELSE BR.BRAND_NAME || ' ' || H.MODEL_NAME
                        END
                END AS MODEL_NAME,
                CASE WHEN H.MODEL_NAME LIKE '%Adapter%' THEN 2 ELSE 1 END AS SORT_ORDER
            FROM
                RE_CC_INST A
                JOIN EVENT_CHARGE B ON A.EVENT_INST_ID = B.EVENT_INST_ID
                JOIN RE_SUBS_ORDER_INST C ON A.EVENT_INST_ID = C.EVENT_INST_ID
                JOIN CRM.ORDER_ITEM D ON D.ORDER_ITEM_ID = C.ORDER_ITEM_ID AND D.CUST_ORDER_ID = C.CUST_ORDER_ID
                JOIN ACCT_ITEM_TYPE F ON F.ACCT_ITEM_TYPE_ID = B.ACCT_ITEM_TYPE_ID
                JOIN CRM.GOODS_ORDER E ON D.ORDER_ITEM_ID = E.ORDER_ITEM_ID
                JOIN CRM.GM_MODEL H ON H.MODEL_ID = E.MODEL_ID
                JOIN CRM.GM_BRAND BR ON H.BRAND_ID=BR.BRAND_ID
                JOIN CRM.AGREEMENT_ORDER M ON D.ORDER_ITEM_ID = M.ORDER_ITEM_ID
                JOIN AGREEMENT AG ON M.AGREEMENT_ID = AG.AGREEMENT_ID
                AND AG.AGREEMENT_TYPE_ID='4'
                AND BR.BRAND_CODE NOT IN ('YES','Others')
                LEFT JOIN CRM.GOODS_ORDER_ATTR I_ADAPTER ON E.GOODS_ORDER_ID = I_ADAPTER.GOODS_ORDER_ID
                    AND I_ADAPTER.ATTR_ID = 907129
                    AND H.MODEL_NAME LIKE '%Adapter%'
                LEFT JOIN CRM.GOODS_ORDER_ATTR I_PHONE ON E.GOODS_ORDER_ID = I_PHONE.GOODS_ORDER_ID
                    AND I_PHONE.ATTR_ID = 2725
                    AND H.MODEL_NAME NOT LIKE '%Adapter%'
            WHERE
                B.BILLING_CYCLE_ID IS NOT NULL
                AND D.SUBS_EVENT_ID = 1
        )
    ) M ON M.CUST_ORDER_ID = P.CUST_ORDER_ID AND M.ACC_NBR = P.ACC_NBR

    UNION ALL

    SELECT
        D.CUST_ORDER_ID,
        D.ACC_NBR,
        D.ACCT_ID,
        A.CHARGE*-1,
        0 AS DISCOUNT_CHARGE,
        NULL AS DISCOUNT_INFO,
        DT.NAME AS FEE_ITEM,
        TO_CHAR(A.State_Date, 'HH' || ':' || 'MIam') AS PAYMENT_TIME,
        TO_CHAR(A.State_Date, 'DD-Mon-YYYY') AS PAYMENT_DATE,
        NULL AS AGREEMENT_PERIOD,
        0 AS TAX_CHARGE,
        0 AS ROUNDING_AMOUNT,
        0 AS TAX_RATE,
        AG.AGREEMENT_SHORT_NAME AS OFFER_NAME,
        NULL AS MODEL_NAME,
        NULL AS GOODS_ORDER_ID
    FROM deposit_charge A
    JOIN RE_SUBS_ORDER_INST B ON A.event_inst_id = B.event_inst_id
    JOIN DEPOSIT_TYPE DT ON DT.DEPOSIT_TYPE_ID=A.DEPOSIT_TYPE_ID
    JOIN event_payment C ON B.event_payment_Id = C.event_payment_Id
    JOIN CRM.ORDER_ITEM D ON B.ORDER_ITEM_ID = D.ORDER_ITEM_ID
    JOIN ACCT_ITEM_TYPE E ON A.ACCT_ITEM_TYPE_ID = E.ACCT_ITEM_TYPE_ID
    JOIN CRM.AGREEMENT_ORDER M ON D.ORDER_ITEM_ID = M.ORDER_ITEM_ID
    JOIN AGREEMENT AG ON M.AGREEMENT_ID = AG.AGREEMENT_ID
    JOIN INSTANT_PAYMENT IP ON IP.EVENT_PAYMENT_ID=B.EVENT_PAYMENT_ID
    WHERE  IP.E_INVOICE_NBR = :E_INVOICE_NBR
      AND D.SUBS_EVENT_ID = 1
      AND A.CHARGE<0
) T
ORDER BY T.CUST_ORDER_ID, T.ACC_NBR, T.CHARGE

-- ===== 10267 SALE_INVOICE_E_INVOICE_INFO =====
SELECT B.CLASS_CODE,B.CLASS_DESC,A.QUANTITY,A.UNIT_PRICE,A.TAX_AMOUNT,A.TOTAL_AMOUNT,C.INVOICE_END_DATE,TO_CHAR(INVOICE_END_DATE, 'DD Mon YYYY') AS FORMATEDDATE_NEW,TO_CHAR(INVOICE_END_DATE, 'DD-Mon-YYYY') AS FORMATEDDATE,TO_CHAR(INVOICE_END_DATE-1, 'DD-Mon-YYYY') AS FORMATEDDATE_YES,C.IRBM_DATE  from E_INVOICE_ITEMISED_FEE A,E_INVOICE_CLASSIFICATION B,E_INVOICE C WHERE
  A.E_INVOICE_ID=C.E_INVOICE_ID
  AND A.CLASS_ID=B.CLASS_ID
  AND  C.E_INVOICE_NBR = :E_INVOICE_NBR

-- ===== 10284 SALE_INVOICE_E_INVOICE_DETALI =====
SELECT T.ITEM_ID, T.ITEM_CODE, T.ITEM_CODE_DESC, T.QUANTITY, T.UNIT_PRICE, T.TAX_AMOUNT, T.TOTAL_AMOUNT, T.AMOUNT FROM
(SELECT 
    ITEM_ID,
    ITEM_CODE,
    'Postpaid Device Price' AS ITEM_CODE_DESC,
    COALESCE(A.QUANTITY, 0) AS QUANTITY,
    COALESCE(A.UNIT_PRICE, 0) AS UNIT_PRICE,
    COALESCE(A.TAX_AMOUNT, 0) AS TAX_AMOUNT,
    COALESCE(A.TOTAL_AMOUNT, 0) AS TOTAL_AMOUNT,
    COALESCE(A.AMOUNT, 0) AS AMOUNT
FROM (
    SELECT '001' AS ITEM_ID,
           '003' AS ITEM_CODE,
           A.QUANTITY,
           A.UNIT_PRICE,
           A.TAX_AMOUNT,
           A.TOTAL_AMOUNT,
           A.AMOUNT
    FROM E_INVOICE C
    LEFT JOIN E_INVOICE_ITEMISED_FEE A
        ON A.E_INVOICE_ID = C.E_INVOICE_ID
    LEFT JOIN E_INVOICE_CLASSIFICATION B
        ON A.CLASS_ID = B.CLASS_ID
    WHERE B.CLASS_ID = 1
    AND C.E_INVOICE_NBR = :E_INVOICE_NBR
) A
UNION ALL
SELECT '001' AS ITEM_ID, '003' AS ITEM_CODE, 'Postpaid Device Price' AS ITEM_CODE_DESC, 0, 0, 0, 0, 0
FROM DUAL) T
WHERE ROWNUM = 1

UNION

SELECT T.ITEM_ID, T.ITEM_CODE, T.ITEM_CODE_DESC, T.QUANTITY, T.UNIT_PRICE, T.TAX_AMOUNT, T.TOTAL_AMOUNT, T.AMOUNT FROM
(SELECT 
    ITEM_ID,
    ITEM_CODE,
    'Data Plan' AS ITEM_CODE_DESC,
    COALESCE(A.QUANTITY, 0) AS QUANTITY,
    COALESCE(A.UNIT_PRICE, 0) AS UNIT_PRICE,
    COALESCE(A.TAX_AMOUNT, 0) AS TAX_AMOUNT,
    COALESCE(A.TOTAL_AMOUNT, 0) AS TOTAL_AMOUNT,
    COALESCE(A.AMOUNT, 0) AS AMOUNT
FROM (
    SELECT '002' AS ITEM_ID,
           '017' AS ITEM_CODE,
           A.QUANTITY,
           A.UNIT_PRICE,
           A.TAX_AMOUNT,
           A.TOTAL_AMOUNT,
           A.AMOUNT
    FROM E_INVOICE C
    LEFT JOIN E_INVOICE_ITEMISED_FEE A
        ON A.E_INVOICE_ID = C.E_INVOICE_ID
    LEFT JOIN E_INVOICE_CLASSIFICATION B
        ON A.CLASS_ID = B.CLASS_ID
    WHERE B.CLASS_ID = 2
    AND C.E_INVOICE_NBR = :E_INVOICE_NBR
) A
UNION ALL
SELECT '002' AS ITEM_ID, '017' AS ITEM_CODE, 'Data Plan' AS ITEM_CODE_DESC, 0, 0, 0, 0, 0
FROM DUAL) T
WHERE ROWNUM = 1

UNION

SELECT T.ITEM_ID, T.ITEM_CODE, T.ITEM_CODE_DESC, T.QUANTITY, T.UNIT_PRICE, T.TAX_AMOUNT, T.TOTAL_AMOUNT, T.AMOUNT FROM
(SELECT 
    ITEM_ID,
    ITEM_CODE,
    'Others(6% SST)' AS ITEM_CODE_DESC,
    COALESCE(A.QUANTITY, 0) AS QUANTITY,
    COALESCE(A.UNIT_PRICE, 0) AS UNIT_PRICE,
    COALESCE(A.TAX_AMOUNT, 0) AS TAX_AMOUNT,
    COALESCE(A.TOTAL_AMOUNT, 0) AS TOTAL_AMOUNT,
    COALESCE(A.AMOUNT, 0) AS AMOUNT
FROM (
    SELECT '003' AS ITEM_ID,
           '022' AS ITEM_CODE,
           A.QUANTITY,
           A.UNIT_PRICE,
           A.TAX_AMOUNT,
           A.TOTAL_AMOUNT,
           A.AMOUNT
    FROM E_INVOICE C
    LEFT JOIN E_INVOICE_ITEMISED_FEE A
        ON A.E_INVOICE_ID = C.E_INVOICE_ID
    LEFT JOIN E_INVOICE_CLASSIFICATION B
        ON A.CLASS_ID = B.CLASS_ID
    WHERE B.CLASS_ID = 3
    AND C.E_INVOICE_NBR = :E_INVOICE_NBR
) A
UNION ALL
SELECT '003' AS ITEM_ID, '022' AS ITEM_CODE, 'Others(6% SST)' AS ITEM_CODE_DESC, 0, 0, 0, 0, 0
FROM DUAL) T
WHERE ROWNUM = 1

UNION

SELECT T.ITEM_ID, T.ITEM_CODE, T.ITEM_CODE_DESC, T.QUANTITY, T.UNIT_PRICE, T.TAX_AMOUNT, T.TOTAL_AMOUNT, T.AMOUNT FROM
(SELECT 
    ITEM_ID,
    ITEM_CODE,
    'Others(no SST)' AS ITEM_CODE_DESC,
    COALESCE(A.QUANTITY, 0) AS QUANTITY,
    COALESCE(A.UNIT_PRICE, 0) AS UNIT_PRICE,
    COALESCE(A.TAX_AMOUNT, 0) AS TAX_AMOUNT,
    COALESCE(A.TOTAL_AMOUNT, 0) AS TOTAL_AMOUNT,
    COALESCE(A.AMOUNT, 0) AS AMOUNT
FROM (
    SELECT '004' AS ITEM_ID,
           '022' AS ITEM_CODE,
           A.QUANTITY,
           A.UNIT_PRICE,
           A.TAX_AMOUNT,
           A.TOTAL_AMOUNT,
           A.AMOUNT
    FROM E_INVOICE C
    LEFT JOIN E_INVOICE_ITEMISED_FEE A
        ON A.E_INVOICE_ID = C.E_INVOICE_ID
    LEFT JOIN E_INVOICE_CLASSIFICATION B
        ON A.CLASS_ID = B.CLASS_ID
    WHERE B.CLASS_ID = 4
    AND C.E_INVOICE_NBR = :E_INVOICE_NBR
) A
UNION ALL
SELECT '004' AS ITEM_ID, '022' AS ITEM_CODE, 'Others(no SST)' AS ITEM_CODE_DESC, 0, 0, 0, 0, 0
FROM DUAL) T
WHERE ROWNUM = 1


UNION

SELECT T.ITEM_ID, T.ITEM_CODE, T.ITEM_CODE_DESC, T.QUANTITY, T.UNIT_PRICE, T.TAX_AMOUNT, T.TOTAL_AMOUNT, T.AMOUNT FROM
(SELECT 
    ITEM_ID,
    ITEM_CODE,
    'Others(8% SST)' AS ITEM_CODE_DESC,
    COALESCE(A.QUANTITY, 0) AS QUANTITY,
    COALESCE(A.UNIT_PRICE, 0) AS UNIT_PRICE,
    COALESCE(A.TAX_AMOUNT, 0) AS TAX_AMOUNT,
    COALESCE(A.TOTAL_AMOUNT, 0) AS TOTAL_AMOUNT,
    COALESCE(A.AMOUNT, 0) AS AMOUNT
FROM (
    SELECT '005' AS ITEM_ID,
           '022' AS ITEM_CODE,
           A.QUANTITY,
           A.UNIT_PRICE,
           A.TAX_AMOUNT,
           A.TOTAL_AMOUNT,
           A.AMOUNT
    FROM E_INVOICE C
    LEFT JOIN E_INVOICE_ITEMISED_FEE A
        ON A.E_INVOICE_ID = C.E_INVOICE_ID
    LEFT JOIN E_INVOICE_CLASSIFICATION B
        ON A.CLASS_ID = B.CLASS_ID
    WHERE B.CLASS_ID = 5
    AND C.E_INVOICE_NBR = :E_INVOICE_NBR
) A
UNION ALL
SELECT '005' AS ITEM_ID, '022' AS ITEM_CODE, 'Others(8% SST)' AS ITEM_CODE_DESC, 0, 0, 0, 0, 0
FROM DUAL) T
WHERE ROWNUM = 1

UNION

SELECT T.ITEM_ID, T.ITEM_CODE, T.ITEM_CODE_DESC, T.QUANTITY, T.UNIT_PRICE, T.TAX_AMOUNT, T.TOTAL_AMOUNT, T.AMOUNT FROM
(SELECT 
    ITEM_ID,
    ITEM_CODE,
    'Others(Rewards Redemption/Cash Voucher)' AS ITEM_CODE_DESC,
    COALESCE(A.QUANTITY, 0) AS QUANTITY,
    COALESCE(A.UNIT_PRICE, 0) AS UNIT_PRICE,
    COALESCE(A.TAX_AMOUNT, 0) AS TAX_AMOUNT,
    COALESCE(A.TOTAL_AMOUNT, 0) AS TOTAL_AMOUNT,
    COALESCE(A.AMOUNT, 0) AS AMOUNT
FROM (
    SELECT '006' AS ITEM_ID,
           '022' AS ITEM_CODE,
           A.QUANTITY,
           A.UNIT_PRICE,
           A.TAX_AMOUNT,
           A.TOTAL_AMOUNT,
           A.AMOUNT
    FROM E_INVOICE C
    LEFT JOIN E_INVOICE_ITEMISED_FEE A
        ON A.E_INVOICE_ID = C.E_INVOICE_ID
    LEFT JOIN E_INVOICE_CLASSIFICATION B
        ON A.CLASS_ID = B.CLASS_ID
    WHERE B.CLASS_ID = 6
    AND C.E_INVOICE_NBR = :E_INVOICE_NBR
) A
UNION ALL
SELECT '006' AS ITEM_ID, '022' AS ITEM_CODE, 'Others(Rewards Redemption/Cash Voucher)' AS ITEM_CODE_DESC, 0, 0, 0, 0, 0
FROM DUAL) T
WHERE ROWNUM = 1

-- ===== 10288 SALE_INVOICE_E_INVOICE_TOTAL =====
SELECT B.CLASS_CODE,B.CLASS_DESC,A.QUANTITY,A.UNIT_PRICE,A.AMOUNT,A.TAX_AMOUNT,A.TOTAL_AMOUNT,C.INVOICE_END_DATE, TO_CHAR(INVOICE_END_DATE, 'DD Mon YYYY') AS FORMATEDDATE,TO_CHAR(INVOICE_END_DATE-1, 'DD Mon YYYY') AS FORMATEDDATE_YES,C.IRBM_DATE  from E_INVOICE_ITEMISED_FEE A,E_INVOICE_CLASSIFICATION B,E_INVOICE C WHERE
  A.E_INVOICE_ID=C.E_INVOICE_ID
  AND A.CLASS_ID=B.CLASS_ID
  AND C.E_INVOICE_NBR= :E_INVOICE_NBR

-- ===== 10324 SALE_INVOICE_CREDIT_INFO =====
select 
       A.ACCT_ID,
       B.CREDIT_LIMIT
   
 from e_invoice A,
      CC_ACCT B
where A.ACCT_id = B.ACCT_ID
  and A.E_INVOICE_NBR  = :E_INVOICE_NBR

-- ===== 10344 SALE_INVOICE_ROUNDING_INFO =====
SELECT  SUM(B.CHARGE)AS ROUNDING_AMOUNT

    FROM  EVENT_CHARGE B, ACCT_ITEM_TYPE C
    WHERE B.ACCT_ITEM_TYPE_ID= C.ACCT_ITEM_TYPE_ID
    AND C.ACCT_ITEM_TYPE_CODE  IN ('ZRL','ROUNDING')
    AND B.BILLING_CYCLE_ID IS NOT NULL
    AND B.E_INVOICE_NBR = :E_INVOICE_NBR

-- ===== 10444 SALE_INVOICE_BA_ADDRESS_INFO =====
SELECT 
    TRIM(
        CASE WHEN A.STREET_NO IS NOT NULL THEN A.STREET_NO || ' ' ELSE '' END ||
        CASE WHEN A.STREET_NAME IS NOT NULL THEN A.STREET_NAME || ', ' ELSE '' END ||
        CASE WHEN A.BUILDING_NAME IS NOT NULL THEN A.BUILDING_NAME || ', ' ELSE '' END ||
        CASE WHEN A.EXT_ADDRESS1 IS NOT NULL THEN A.EXT_ADDRESS1 || ', ' ELSE '' END ||
        CASE WHEN A.CITY IS NOT NULL THEN A.CITY || ', ' ELSE '' END ||
        CASE WHEN A.STATE IS NOT NULL THEN A.STATE || ', ' ELSE '' END ||
        CASE WHEN A.COUNTRY IS NOT NULL THEN A.COUNTRY || ', ' ELSE '' END ||
        CASE WHEN A.ZIP_CODE IS NOT NULL THEN A.ZIP_CODE ELSE '' END
    ) AS FORMATTED_ADDRESS
  FROM POST_STD_ADDR A, E_INVOICE B, CUST_BILL_DELIVERY_INFO C,ACCT D
 WHERE B.CUST_ID = C.CUST_ID
 AND C.CUST_BILL_DELIVERY_INFO_ID = D.CUST_BILL_DELIVERY_INFO_ID
 AND A.std_addr_id=C.std_addr_id
 AND B.ACCT_ID=D.ACCT_ID
 AND B.E_INVOICE_NBR = :E_INVOICE_NBR

-- ===== 10484 SALE_INVOICE_E_INVOICE_DETALI_PRE =====
SELECT T.ITEM_ID, T.ITEM_CODE, T.ITEM_CODE_DESC, T.QUANTITY, T.UNIT_PRICE, T.TAX_AMOUNT, T.TOTAL_AMOUNT, T.AMOUNT FROM
(SELECT 
    ITEM_ID,
    ITEM_CODE,
    'Prepaid Device Price' AS ITEM_CODE_DESC,
    COALESCE(A.QUANTITY, 0) AS QUANTITY,
    COALESCE(A.UNIT_PRICE, 0) AS UNIT_PRICE,
    COALESCE(A.TAX_AMOUNT, 0) AS TAX_AMOUNT,
    COALESCE(A.TOTAL_AMOUNT, 0) AS TOTAL_AMOUNT,
    COALESCE(A.AMOUNT, 0) AS AMOUNT
FROM (
    SELECT '001' AS ITEM_ID,
           '003' AS ITEM_CODE,
           A.QUANTITY,
           A.UNIT_PRICE,
           A.TAX_AMOUNT,
           A.TOTAL_AMOUNT,
           A.AMOUNT
    FROM E_INVOICE C
    LEFT JOIN E_INVOICE_ITEMISED_FEE A
        ON A.E_INVOICE_ID = C.E_INVOICE_ID
    LEFT JOIN E_INVOICE_CLASSIFICATION B
        ON A.CLASS_ID = B.CLASS_ID
    WHERE B.CLASS_ID = 1
    AND C.E_INVOICE_NBR = :E_INVOICE_NBR
) A
UNION ALL
SELECT '001' AS ITEM_ID, '003' AS ITEM_CODE, 'Prepaid Device Price' AS ITEM_CODE_DESC, 0, 0, 0, 0, 0
FROM DUAL) T
WHERE ROWNUM = 1

UNION

SELECT T.ITEM_ID, T.ITEM_CODE, T.ITEM_CODE_DESC, T.QUANTITY, T.UNIT_PRICE, T.TAX_AMOUNT, T.TOTAL_AMOUNT, T.AMOUNT FROM
(SELECT 
    ITEM_ID,
    ITEM_CODE,
    'Data Plan' AS ITEM_CODE_DESC,
    COALESCE(A.QUANTITY, 0) AS QUANTITY,
    COALESCE(A.UNIT_PRICE, 0) AS UNIT_PRICE,
    COALESCE(A.TAX_AMOUNT, 0) AS TAX_AMOUNT,
    COALESCE(A.TOTAL_AMOUNT, 0) AS TOTAL_AMOUNT,
    COALESCE(A.AMOUNT, 0) AS AMOUNT
FROM (
    SELECT '002' AS ITEM_ID,
           '017' AS ITEM_CODE,
           A.QUANTITY,
           A.UNIT_PRICE,
           A.TAX_AMOUNT,
           A.TOTAL_AMOUNT,
           A.AMOUNT
    FROM E_INVOICE C
    LEFT JOIN E_INVOICE_ITEMISED_FEE A
        ON A.E_INVOICE_ID = C.E_INVOICE_ID
    LEFT JOIN E_INVOICE_CLASSIFICATION B
        ON A.CLASS_ID = B.CLASS_ID
    WHERE B.CLASS_ID = 2
    AND C.E_INVOICE_NBR = :E_INVOICE_NBR
) A
) T
WHERE ROWNUM = 1

UNION

SELECT T.ITEM_ID, T.ITEM_CODE, T.ITEM_CODE_DESC, T.QUANTITY, T.UNIT_PRICE, T.TAX_AMOUNT, T.TOTAL_AMOUNT, T.AMOUNT FROM
(SELECT 
    ITEM_ID,
    ITEM_CODE,
    'Others/Prepaid Registration/Prepaid
Reload/ Prepaid Add-on' AS ITEM_CODE_DESC,
    COALESCE(A.QUANTITY, 0) AS QUANTITY,
    COALESCE(A.UNIT_PRICE, 0) AS UNIT_PRICE,
    COALESCE(A.TAX_AMOUNT, 0) AS TAX_AMOUNT,
    COALESCE(A.TOTAL_AMOUNT, 0) AS TOTAL_AMOUNT,
    COALESCE(A.AMOUNT, 0) AS AMOUNT
FROM (
    SELECT '003' AS ITEM_ID,
           '022' AS ITEM_CODE,
           A.QUANTITY,
           A.UNIT_PRICE,
           A.TAX_AMOUNT,
           A.TOTAL_AMOUNT,
           A.AMOUNT
    FROM E_INVOICE C
    LEFT JOIN E_INVOICE_ITEMISED_FEE A
        ON A.E_INVOICE_ID = C.E_INVOICE_ID
    LEFT JOIN E_INVOICE_CLASSIFICATION B
        ON A.CLASS_ID = B.CLASS_ID
    WHERE B.CLASS_ID = 3
    AND C.E_INVOICE_NBR = :E_INVOICE_NBR
) A
) T
UNION

SELECT T.ITEM_ID, T.ITEM_CODE, T.ITEM_CODE_DESC, T.QUANTITY, T.UNIT_PRICE, T.TAX_AMOUNT, T.TOTAL_AMOUNT, T.AMOUNT FROM
(SELECT 
    ITEM_ID,
    ITEM_CODE,
    'Others/Prepaid Registration/Prepaid
Reload/ Prepaid Add-on' AS ITEM_CODE_DESC,
    COALESCE(A.QUANTITY, 0) AS QUANTITY,
    COALESCE(A.UNIT_PRICE, 0) AS UNIT_PRICE,
    COALESCE(A.TAX_AMOUNT, 0) AS TAX_AMOUNT,
    COALESCE(A.TOTAL_AMOUNT, 0) AS TOTAL_AMOUNT,
    COALESCE(A.AMOUNT, 0) AS AMOUNT
FROM (
    SELECT '004' AS ITEM_ID,
           '022' AS ITEM_CODE,
           A.QUANTITY,
           A.UNIT_PRICE,
           A.TAX_AMOUNT,
           A.TOTAL_AMOUNT,
           A.AMOUNT
    FROM E_INVOICE C
    LEFT JOIN E_INVOICE_ITEMISED_FEE A
        ON A.E_INVOICE_ID = C.E_INVOICE_ID
    LEFT JOIN E_INVOICE_CLASSIFICATION B
        ON A.CLASS_ID = B.CLASS_ID
    WHERE B.CLASS_ID = 4
    AND C.E_INVOICE_NBR = :E_INVOICE_NBR
) A) T

UNION

SELECT T.ITEM_ID, T.ITEM_CODE, T.ITEM_CODE_DESC, T.QUANTITY, T.UNIT_PRICE, T.TAX_AMOUNT, T.TOTAL_AMOUNT, T.AMOUNT FROM
(SELECT 
    ITEM_ID,
    ITEM_CODE,
    'Payment(Rewards Redemption/Cash Voucher)' AS ITEM_CODE_DESC,
    COALESCE(A.QUANTITY, 0) AS QUANTITY,
    COALESCE(A.UNIT_PRICE, 0) AS UNIT_PRICE,
    COALESCE(A.TAX_AMOUNT, 0) AS TAX_AMOUNT,
    COALESCE(A.TOTAL_AMOUNT, 0) AS TOTAL_AMOUNT,
    COALESCE(A.AMOUNT, 0) AS AMOUNT
FROM (
    SELECT '007' AS ITEM_ID,
           '022' AS ITEM_CODE,
           A.QUANTITY,
           A.UNIT_PRICE,
           A.TAX_AMOUNT,
           A.TOTAL_AMOUNT,
           A.AMOUNT
    FROM E_INVOICE C
    LEFT JOIN E_INVOICE_ITEMISED_FEE A
        ON A.E_INVOICE_ID = C.E_INVOICE_ID
    LEFT JOIN E_INVOICE_CLASSIFICATION B
        ON A.CLASS_ID = B.CLASS_ID
    WHERE B.CLASS_ID = 7
    AND C.E_INVOICE_NBR = :E_INVOICE_NBR
) A) T

-- ===== 10507 SALE_INVOICE_ADDON_INFO =====
select  distinct  b.order_item_id,TO_CHAR(p.eff_date, 'DD Mon YYYY') AS EFF_DATE,c.Offer_Name || '(' || 
       TO_CHAR(p.eff_date, 'DD Mon YYYY', 'NLS_DATE_LANGUAGE = American') || '-' || 
       TO_CHAR(p.exp_date, 'DD Mon YYYY', 'NLS_DATE_LANGUAGE = American') || ')' as Offer_name,0 as charge from crm.dp_offer_order a,crm.order_item b,offer c,crm.re_subs_order_inst j,CC.EVENT_CHARGE O,cc.subs_upp_inst p  where 
a.order_Item_id=b.order_Item_id
and a.offer_id=c.offer_id
and p.subs_upp_inst_id=a.offer_inst_Id
AND O.EVENT_INST_ID=J.EVENT_INST_ID
and j.cust_order_id=b.cust_order_Id
and c.offer_code in ('PRD10023','PRD10025')
AND O.DEDUCT_SEQ=1
and b.subs_event_Id=1
and o.state=4
AND O.E_INVOICE_NBR =:E_INVOICE_NBR
union all

select  distinct b.order_Item_id,TO_CHAR(p.eff_date, 'DD-Mon-YYYY') AS EFF_DATE,c.Offer_Name || '(' || 
       TO_CHAR(p.eff_date, 'DD-Mon-YYYY', 'NLS_DATE_LANGUAGE = American') || '-' || 
       TO_CHAR(p.exp_date, 'DD-Mon-YYYY', 'NLS_DATE_LANGUAGE = American') || ')' as Offer_name, o.charge*1.08 from crm.dp_offer_order a,crm.order_item b,offer c,crm.re_subs_order_inst j,CC.EVENT_CHARGE O,cc.subs_upp_inst p  where 
a.order_Item_id=b.order_Item_id
and a.offer_id=c.offer_id
and p.subs_upp_inst_id=a.offer_inst_Id
AND O.EVENT_INST_ID=J.EVENT_INST_ID
and j.cust_order_id=b.cust_order_Id
and c.offer_code in ('PRD10024')
AND O.DEDUCT_SEQ=1
and b.subs_event_Id=1
and o.state=4
and o.acct_Item_type_Id=4405
AND O.E_INVOICE_NBR =:E_INVOICE_NBR

-- ===== 10525 SALE_INVOICE_TAX_FLAG =====
select B.ATTR_VALUE AS TAX_FLAG
                from ATTR A, ACCT_ATTR_VALUE B,e_invoice C
               where A.ATTR_CODE = 'IS_TAX_EXEMPTION'
                 and A.ATTR_ID = B.ATTR_ID
                 and B.ACCT_ID = C.ACCT_ID
                 AND C.E_INVOICE_NBR  = :E_INVOICE_NBR

-- ===== 10544 SALE_INVOICE_ADVANCE_PAYMENT_INFO_CANCEL =====
SELECT 
SUM(COALESCE(B.CHARGE,0) + COALESCE(T.CHARGE,0))

AS TOTAL_ADVANCE_PAYMENT
  
FROM (
    -- 主费用记录
    SELECT 
        B.DEDUCT_SEQ,
        B.PRICE_ID,
  
        B.CHARGE,
        F.ACCT_ITEM_TYPE_NAME AS FEE_ITEM,
        TO_CHAR(B.State_Date, 'HH:MIam') AS PAYMENT_TIME
    FROM EVENT_CHARGE B , ACCT_ITEM_TYPE F, EVENT_CHARGE_EXT H
    where  F.ACCT_ITEM_TYPE_ID = B.ACCT_ITEM_TYPE_ID
    AND B.BILLING_CYCLE_ID IS NOT NULL
    AND B.REVERSE_E_INVOICE_NBR = :E_INVOICE_NBR
    AND H.EVENT_INST_ID = B.EVENT_INST_ID
    AND H.PRICE_ID = B.PRICE_Id
 
    AND H.SEQ = B.SEQ
    AND H.DEDUCT_SEQ = B.DEDUCT_SEQ
    AND H.IS_TAX IS NULL
    AND F.ACCT_ITEM_TYPE_CODE='PLAN_ADVANCE_PAYMENT'
) B
-- 关联税项记录
left JOIN (
     SELECT 
        B.DEDUCT_SEQ,
        B.PRICE_ID,
        B.CHARGE,
        F.ACCT_ITEM_TYPE_NAME AS FEE_ITEM,
        TO_CHAR(B.State_Date, 'HH:MIam') AS PAYMENT_TIME
    FROM EVENT_CHARGE B , ACCT_ITEM_TYPE F, EVENT_CHARGE_EXT H
    where  F.ACCT_ITEM_TYPE_ID = B.ACCT_ITEM_TYPE_ID
    AND B.BILLING_CYCLE_ID IS NOT NULL
    AND B.REVERSE_E_INVOICE_NBR = :E_INVOICE_NBR
    AND H.EVENT_INST_ID = B.EVENT_INST_ID
    AND H.PRICE_ID = B.PRICE_Id
 
    AND H.SEQ = B.SEQ
    AND H.DEDUCT_SEQ = B.DEDUCT_SEQ
    AND H.IS_TAX='Y'
     
) T ON T.PRICE_ID = B.PRICE_ID 
    AND T.DEDUCT_SEQ <> B.DEDUCT_SEQ

-- ===== 10545 SALE_INVOICE_PAYMENT_SUMMARY_INFO_CANCEL =====
SELECT NVL(MAIN_FEE.TOTAL_AMOUNT, 0) + NVL(DEPOSIT_FEE.DEPOSIT_AMOUNT, 0) AS TOTAL_AMOUNT
  FROM ( -- 主费用部分
        SELECT SUM(B.CHARGE) AS TOTAL_AMOUNT
          FROM EVENT_CHARGE B
          JOIN ACCT_ITEM_TYPE C
            ON B.ACCT_ITEM_TYPE_ID = C.ACCT_ITEM_TYPE_ID
         WHERE C.ACCT_ITEM_TYPE_CODE NOT IN ('ZRL', 'ROUNDING')
           AND B.BILLING_CYCLE_ID IS NOT NULL
           AND B.REVERSE_E_INVOICE_NBR =:E_INVOICE_NBR) MAIN_FEE,
       ( -- 押金部分（转换为相同单位）
        SELECT
        
         SUM(B.CHARGE) AS DEPOSIT_AMOUNT
          FROM DEPOSIT_ITEM B
          JOIN INSTANT_PAYMENT E
            ON B.EVENT_PAYMENT_ID = E.EVENT_PAYMENT_ID
          JOIN INSTANT_PAYMENT P
            ON E.PAYMENT_iD = P.REVERSED_PAYMENT_iD
        
         WHERE P.REVERSE_E_INVOICE_NBR = :E_INVOICE_NBR
        
        ) DEPOSIT_FEE

-- ===== 10546 SALE_INVOICE_ROUNDING_INFO_CANCEL =====
SELECT  SUM(B.CHARGE)AS ROUNDING_AMOUNT

    FROM  EVENT_CHARGE B, ACCT_ITEM_TYPE C
    WHERE B.ACCT_ITEM_TYPE_ID= C.ACCT_ITEM_TYPE_ID
    AND C.ACCT_ITEM_TYPE_CODE  IN ('ROUNDING')
    AND B.BILLING_CYCLE_ID IS NOT NULL
    AND B.REVERSE_E_INVOICE_NBR = :E_INVOICE_NBR

-- ===== 10547 SALE_INVOICE_PAYMENTMETHOD_INFO_CANCEL =====
SELECT 
    T.AMOUNT,
    T.CREATED_DATE,
    PM.PAYMENT_METHOD_NAME,
    T.EVENT_PAYMENT_ID
FROM (
    SELECT 
        EVENT_PAYMENT_ID,
        PAYMENT_METHOD_ID,
        SUM(AMOUNT)*-1 AS AMOUNT,
        TO_CHAR(MAX(CREATED_DATE), 'HH:MIam') AS CREATED_DATE
    FROM (
        -- EVENT_CHARGE支付记录
        SELECT 
            B.EVENT_PAYMENT_ID,
            E.PAYMENT_METHOD_ID,
            SUM(B.CHARGE) AS AMOUNT,
            MAX(E.CREATED_DATE) AS CREATED_DATE
        FROM EVENT_CHARGE B
        JOIN INSTANT_PAYMENT E 
            ON B.EVENT_PAYMENT_ID = E.EVENT_PAYMENT_ID
        WHERE B.BILLING_CYCLE_ID IS NOT NULL
            AND B.REVERSE_E_INVOICE_NBR = :E_INVOICE_NBR
        GROUP BY 
            B.EVENT_PAYMENT_ID, 
            E.PAYMENT_METHOD_ID
        
        UNION ALL
        
        -- DEPOSIT_ITEM支付记录
            SELECT 
            P.EVENT_PAYMENT_ID,
            E.PAYMENT_METHOD_ID,
            SUM(B.CHARGE)*-1 AS AMOUNT,
            MAX(E.CREATED_DATE) AS CREATED_DATE
        FROM DEPOSIT_ITEM B
        JOIN INSTANT_PAYMENT E 
            ON B.EVENT_PAYMENT_ID = E.EVENT_PAYMENT_ID
       JOIN INSTANT_PAYMENT P ON E.PAYMENT_iD=P.REVERSED_PAYMENT_iD

        WHERE P.REVERSE_E_INVOICE_NBR = :E_INVOICE_NBR
        GROUP BY 
            P.EVENT_PAYMENT_ID, 
            E.PAYMENT_METHOD_ID
    ) COMBINED
    -- 按支付事件和支付方式分组
    GROUP BY EVENT_PAYMENT_ID, PAYMENT_METHOD_ID
) T
JOIN PAYMENT_METHOD PM 
    ON T.PAYMENT_METHOD_ID = PM.PAYMENT_METHOD_ID
ORDER BY T.CREATED_DATE

-- ===== 10548 SALE_INVOICE_CHARGE_DETAILS_INFO_CANCEL =====
SELECT 
    T.CUST_ORDER_ID,
    T.ACC_NBR,
    T.ACCT_ID,
    T.CHARGE,
    T.FEE_ITEM || ' Refund' AS FEE_ITEM,
    T.PAYMENT_TIME,
    T.PAYMENT_DATE,
    T.TAX_CHARGE,
    T.ROUNDING_AMOUNT,
    T.TAX_RATE,
    T.OFFER_NAME,
    CASE 
        WHEN T.GOODS_ORDER_ID IS NOT NULL AND 
             T.CHARGE = MIN(T.CHARGE) OVER (PARTITION BY T.CUST_ORDER_ID, T.ACC_NBR, T.GOODS_ORDER_ID) 
        THEN T.MODEL_NAME
        ELSE NULL
    END AS MODEL_NAME,
    T.GOODS_ORDER_ID
FROM 
    (SELECT 
        B.CUST_ORDER_ID,
        B.ACC_NBR,
        B.ACCT_ID,
        B.CHARGE AS CHARGE,
        B.FEE_ITEM,
        B.PAYMENT_TIME,
        B.PAYMENT_DATE,
        T.CHARGE AS TAX_CHARGE,
        CASE WHEN ROW_NUMBER() OVER (PARTITION BY B.CUST_ORDER_ID ORDER BY B.DEDUCT_SEQ) = 1 
             THEN NVL(R.ROUNDING_AMOUNT, 0) 
             ELSE 0 
        END AS ROUNDING_AMOUNT,
        B.TAX_RATE,
        B.OFFER_NAME,
        M.GOODS_ORDER_ID,
        CASE 
            WHEN M.MODEL_NAME IS NOT NULL 
            THEN M.MODEL_NAME
            ELSE NULL
        END AS MODEL_NAME
    FROM (
        -- Main fee records
        SELECT 
            D.CUST_ORDER_ID,
            B.DEDUCT_SEQ,
            B.PRICE_ID,
            D.ACC_NBR,
            D.ACCT_ID,
            B.CHARGE,
            F.ACCT_ITEM_TYPE_NAME AS FEE_ITEM,
            TO_CHAR(B.State_Date, 'HH:MIam') AS PAYMENT_TIME,
            TO_CHAR(B.State_Date, 'DD-Mon-YYYY') AS PAYMENT_DATE,
            G.TAX_RATE,
            AG.AGREEMENT_SHORT_NAME AS OFFER_NAME,
            F.ACCT_ITEM_TYPE_ID,
            F.ACCT_ITEM_TYPE_CODE,
            EP.EVENT_PAYMENT_ID
        FROM  EVENT_CHARGE B, RE_SUBS_ORDER_INST C, CRM.ORDER_ITEM D, ACCT_ITEM_TYPE F, EVENT_CHARGE_EXT H, GST_TYPE_TAX_RATE G, OFFER J, GST_TYPE K,CRM.AGREEMENT_ORDER M,AGREEMENT AG,
        EVENT_PAYMENT EP
        WHERE 
         B.EVENT_INST_ID = C.EVENT_INST_ID
        AND D.ORDER_ITEM_ID = C.ORDER_ITEM_ID
       AND F.ACCT_ITEM_TYPE_ID = B.ACCT_ITEM_TYPE_ID
       AND B.BILLING_CYCLE_ID IS NOT NULL
        AND B.REVERSE_E_INVOICE_NBR = :E_INVOICE_NBR
        AND H.EVENT_INST_ID = B.EVENT_INST_ID
        AND H.PRICE_ID = B.PRICE_ID
        AND D.SUBS_PLAN_ID = J.OFFER_iD
        AND C.CUST_ORDER_ID = D.CUST_ORDER_ID
        AND H.SEQ = B.SEQ
        AND F.GST_TYPE = K.GST_TYPE
        AND F.GST_TYPE <> 'Z'
        AND H.DEDUCT_SEQ = B.DEDUCT_SEQ
        AND H.IS_TAX IS NULL
        AND F.GST_TYPE = G.GST_TYPE
        AND D.ORDER_ITEM_ID=M.ORDER_ITEM_ID
        AND M.AGREEMENT_ID = AG.AGREEMENT_ID
        AND C.EVENT_PAYMENT_ID=EP.EVENT_PAYMENT_ID
        AND D.SUBS_EVENT_ID=1
    ) B
    -- Tax records
    LEFT JOIN (
        SELECT 
            D.CUST_ORDER_ID,
            B.DEDUCT_SEQ,
            B.PRICE_ID,
            B.CHARGE,
            D.ACC_NBR
        FROM EVENT_CHARGE B, RE_SUBS_ORDER_INST C, CRM.ORDER_ITEM D, EVENT_CHARGE_EXT H,EVENT_PAYMENT EP
        WHERE  B.EVENT_INST_ID = C.EVENT_INST_ID
        AND D.ORDER_ITEM_ID = C.ORDER_ITEM_ID
        AND B.BILLING_CYCLE_ID IS NOT NULL
        AND B.REVERSE_E_INVOICE_NBR = :E_INVOICE_NBR
        AND H.EVENT_INST_ID = B.EVENT_INST_ID
        AND H.PRICE_ID = B.PRICE_ID
        AND H.SEQ = B.SEQ
        AND C.EVENT_PAYMENT_ID=EP.EVENT_PAYMENT_ID
        AND C.CUST_ORDER_ID = D.CUST_ORDER_ID
        AND H.DEDUCT_SEQ = B.DEDUCT_SEQ
        AND H.IS_TAX = 'Y'
        AND D.SUBS_EVENT_ID=1
    ) T ON T.PRICE_ID = B.PRICE_ID 
        AND T.DEDUCT_SEQ <> B.DEDUCT_SEQ 
        AND T.ACC_NBR = B.ACC_NBR
        AND T.CUST_ORDER_ID = B.CUST_ORDER_ID
    -- Rounding amount
    LEFT JOIN (
        SELECT 
    D.CUST_ORDER_ID,
    MAX(B.CHARGE) AS ROUNDING_AMOUNT  -- or another aggregate function
FROM  EVENT_CHARGE B, RE_SUBS_ORDER_INST C, CRM.ORDER_ITEM D, ACCT_ITEM_TYPE F
WHERE  B.EVENT_INST_ID = C.EVENT_INST_ID
AND D.ORDER_ITEM_ID = C.ORDER_ITEM_ID
AND C.CUST_ORDER_ID = D.CUST_ORDER_ID
AND D.SUBS_EVENT_ID=1
AND F.ACCT_ITEM_TYPE_ID = B.ACCT_ITEM_TYPE_ID
AND B.BILLING_CYCLE_ID IS NOT NULL
AND B.REVERSE_E_INVOICE_NBR = :E_INVOICE_NBR
AND F.ACCT_ITEM_TYPE_CODE IN ('ROUNDING')
GROUP BY D.CUST_ORDER_ID
    ) R ON R.CUST_ORDER_ID = B.CUST_ORDER_ID
    LEFT JOIN (
    ---- GOODS Info
    SELECT  
     DISTINCT 
        D.CUST_ORDER_ID,
        E.GOODS_ORDER_ID,
        D.ACC_NBR,
        CASE 
            WHEN I.VALUE IS NOT NULL 
            THEN H.MODEL_NAME || ',' || I.VALUE  
            ELSE H.MODEL_NAME                  
        END AS MODEL_NAME
    FROM 
         EVENT_CHARGE B
        JOIN RE_SUBS_ORDER_INST C ON C.EVENT_INST_ID = B.EVENT_INST_ID
        JOIN CRM.ORDER_ITEM D ON D.ORDER_ITEM_ID = C.ORDER_ITEM_ID AND D.CUST_ORDER_ID = C.CUST_ORDER_ID
        JOIN ACCT_ITEM_TYPE F ON F.ACCT_ITEM_TYPE_ID = B.ACCT_ITEM_TYPE_ID
        JOIN CRM.GOODS_ORDER E ON D.ORDER_ITEM_ID = E.ORDER_ITEM_ID
        JOIN CRM.GM_MODEL H ON H.MODEL_ID = E.MODEL_ID
        JOIN CRM.GM_BRAND BR ON H.BRAND_ID=BR.BRAND_ID 
        AND BR.BRAND_CODE<>'Others'
        JOIN CRM.AGREEMENT_ORDER M ON D.ORDER_ITEM_ID = M.ORDER_ITEM_ID
        JOIN AGREEMENT AG ON M.AGREEMENT_ID = AG.AGREEMENT_ID
        AND AG.AGREEMENT_TYPE_ID='4'
        LEFT JOIN CRM.GOODS_ORDER_ATTR I ON E.GOODS_ORDER_ID = I.GOODS_ORDER_ID 
        AND I.ATTR_ID = 2725 
    WHERE 
        B.BILLING_CYCLE_ID IS NOT NULL
        AND B.REVERSE_E_INVOICE_NBR = :E_INVOICE_NBR
        AND D.SUBS_EVENT_ID = 1
    ) M ON M.CUST_ORDER_ID = B.CUST_ORDER_ID
    AND M.ACC_NBR=B.ACC_nBR 

    UNION
    --tax
    SELECT 
        P.CUST_ORDER_ID,
        P.ACC_NBR,
        P.ACCT_ID,
        P.CHARGE AS CHARGE,
        P.FEE_ITEM,
        P.PAYMENT_TIME,
        P.PAYMENT_DATE,
        P.TAX_CHARGE AS TAX_CHARGE,
        P.ROUNDING_AMOUNT,
        P.TAX_RATE,
        P.OFFER_NAME,
        M.GOODS_ORDER_ID,
        CASE 
            WHEN M.MODEL_NAME IS NOT NULL 
            THEN M.MODEL_NAME
            ELSE NULL
        END AS MODEL_NAME

from


    ( SELECT 
        D.CUST_ORDER_ID,
        D.ACC_NBR,
        D.ACCT_ID,
        B.CHARGE AS CHARGE,
        F.ACCT_ITEM_TYPE_NAME AS FEE_ITEM,
        TO_CHAR(B.State_Date, 'HH:MIam') AS PAYMENT_TIME,
        TO_CHAR(B.State_Date, 'DD-Mon-YYYY') AS PAYMENT_DATE,
        0 AS TAX_CHARGE,
        0 AS ROUNDING_AMOUNT,
        J.TAX_RATE,
        AG.AGREEMENT_SHORT_NAME AS OFFER_NAME
    FROM  EVENT_CHARGE B, RE_SUBS_ORDER_INST C, CRM.ORDER_ITEM D, ACCT_ITEM_TYPE F,GST_TYPE H,GST_TYPE_TAX_RATE J,OFFER K,CRM.AGREEMENT_ORDER M,AGREEMENT AG
    WHERE  B.EVENT_INST_ID = C.EVENT_INST_ID
    AND D.ORDER_ITEM_ID = C.ORDER_ITEM_ID
    AND F.GST_TYPE = H.GST_TYPE
    AND D.SUBS_PLAN_ID=K.OFFER_ID
    AND D.SUBS_EVENT_ID=1
    AND D.CUST_ORDER_ID = C.CUST_ORDER_ID
    AND F.ACCT_ITEM_TYPE_ID = B.ACCT_ITEM_TYPE_ID
    AND B.BILLING_CYCLE_ID IS NOT NULL
    AND B.REVERSE_E_INVOICE_NBR = :E_INVOICE_NBR
    AND H.GST_TYPE = 'Z'
    AND D.ORDER_ITEM_ID=M.ORDER_ITEM_ID
    AND M.AGREEMENT_ID = AG.AGREEMENT_ID
    AND H.GST_TYPE=J.GST_TYPE
    AND F.ACCT_ITEM_TYPE_CODE not in ('ZRL','ROUNDING')
    ) P
    LEFT JOIN (
    ---- GOODS Info
    SELECT  
     DISTINCT 
        D.CUST_ORDER_ID,
        E.GOODS_ORDER_ID,
        D.ACC_NBR,
        CASE 
            WHEN I.VALUE IS NOT NULL 
            THEN H.MODEL_NAME || ',' || I.VALUE  
            ELSE H.MODEL_NAME                  
        END AS MODEL_NAME
    FROM 
         EVENT_CHARGE B
        JOIN RE_SUBS_ORDER_INST C ON B.EVENT_INST_ID = C.EVENT_INST_ID
        JOIN CRM.ORDER_ITEM D ON D.ORDER_ITEM_ID = C.ORDER_ITEM_ID AND D.CUST_ORDER_ID = C.CUST_ORDER_ID
        JOIN ACCT_ITEM_TYPE F ON F.ACCT_ITEM_TYPE_ID = B.ACCT_ITEM_TYPE_ID
        JOIN CRM.GOODS_ORDER E ON D.ORDER_ITEM_ID = E.ORDER_ITEM_ID
        JOIN CRM.GM_MODEL H ON H.MODEL_ID = E.MODEL_ID
        JOIN CRM.GM_BRAND BR ON H.BRAND_ID=BR.BRAND_ID 
        JOIN CRM.AGREEMENT_ORDER M ON D.ORDER_ITEM_ID = M.ORDER_ITEM_ID
        JOIN AGREEMENT AG ON M.AGREEMENT_ID = AG.AGREEMENT_ID
        AND AG.AGREEMENT_TYPE_ID='4'
        AND BR.BRAND_CODE<>'Others'
        LEFT JOIN CRM.GOODS_ORDER_ATTR I ON E.GOODS_ORDER_ID = I.GOODS_ORDER_ID 
        AND I.ATTR_ID = 2725 
    WHERE 
        B.BILLING_CYCLE_ID IS NOT NULL
        AND D.SUBS_EVENT_ID = 1
    ) M ON M.CUST_ORDER_ID = P.CUST_ORDER_ID
    AND M.ACC_NBR=P.ACC_nBR
    
    UNION
      SELECT 
        D.CUST_ORDER_ID,
        D.ACC_NBR,
        D.ACCT_ID,
        A.CHARGE,
        E.ACCT_ITEM_TYPE_NAME AS FEE_ITEM,
        TO_CHAR(IP.CREATED_DATE, 'HH:MIam') AS PAYMENT_TIME,
        TO_CHAR(IP.CREATED_DATE, 'DD-Mon-YYYY') AS PAYMENT_DATE,
        0 AS TAX_CHARGE,
        0 AS ROUNDING_AMOUNT,
        0 AS TAX_RATE,
        AG.AGREEMENT_SHORT_NAME AS OFFER_NAME,
        NULL AS MODEL_NAME,  
        NULL AS GOODS_ORDER_ID
    FROM deposit_charge A
    JOIN RE_SUBS_ORDER_INST B ON A.event_inst_id = B.event_inst_id
    JOIN event_payment C ON B.event_payment_Id = C.event_payment_Id
    JOIN CRM.ORDER_ITEM D ON B.ORDER_ITEM_ID = D.ORDER_ITEM_ID
    JOIN ACCT_ITEM_TYPE E ON A.ACCT_ITEM_TYPE_ID = E.ACCT_ITEM_TYPE_ID
    JOIN CRM.AGREEMENT_ORDER M ON D.ORDER_ITEM_ID = M.ORDER_ITEM_ID
    JOIN AGREEMENT AG ON M.AGREEMENT_ID = AG.AGREEMENT_ID
        JOIN INSTANT_PAYMENT P ON P.EVENT_PAYMENT_ID=B.EVENT_PAYMENT_ID
    JOIN INSTANT_PAYMENT IP ON IP.REVERSED_PAYMENT_ID=P.PAYMENT_ID
    WHERE  IP.REVERSE_E_INVOICE_NBR = :E_INVOICE_NBR
      AND D.SUBS_EVENT_ID = 1
      AND A.CHARGE<0
    
     )T
   ORDER BY T.CUST_ORDER_ID, T.ACC_NBR, T.CHARGE DESC

-- ===== 10549 SALE_INVOICE_DEPOSIT_INFO_CANCEL =====
SELECT  SUM(A.CHARGE)/10000*-1 AS DEPOSIT FROM DEPOSIT_ITEM A ,EVENT_PAYMENT B, INSTANT_PAYMENT C WHERE 
A.ACCT_ID=B.ACCT_ID
AND A.EVENT_PAYMENT_ID=B.EVENT_PAYMENT_ID
AND C.EVENT_PAYMENT_ID=B.EVENT_PAYMENT_ID
AND C.REVERSE_E_INVOICE_NBR = :E_INVOICE_NBR

-- ===== 10550 SALE_INVOICE_PAYMENTMETHOD_INFO_REWARDS =====
SELECT 
    T.AMOUNT,
    T.CREATED_DATE,
    PM.PAYMENT_METHOD_NAME,
    T.EVENT_PAYMENT_ID
FROM (
    SELECT 
        EVENT_PAYMENT_ID,
        PAYMENT_METHOD_ID,
        SUM(AMOUNT) AS AMOUNT,
        TO_CHAR(MAX(CREATED_DATE), 'HH:MIam') AS CREATED_DATE
    FROM (
        -- EVENT_CHARGE支付记录
        SELECT 
            B.EVENT_PAYMENT_ID,
            E.PAYMENT_METHOD_ID,
            SUM(B.CHARGE) AS AMOUNT,
            MAX(E.CREATED_DATE) AS CREATED_DATE
        FROM EVENT_CHARGE B
        JOIN INSTANT_PAYMENT E 
            ON B.EVENT_PAYMENT_ID = E.EVENT_PAYMENT_ID
        WHERE B.BILLING_CYCLE_ID IS NOT NULL
            AND B.E_INVOICE_NBR = :E_INVOICE_NBR
        GROUP BY 
            B.EVENT_PAYMENT_ID, 
            E.PAYMENT_METHOD_ID
        
        UNION ALL
        
        -- DEPOSIT_ITEM支付记录
        SELECT 
            B.EVENT_PAYMENT_ID,
            E.PAYMENT_METHOD_ID,
            SUM(B.CHARGE)*-1 AS AMOUNT,
            MAX(E.CREATED_DATE) AS CREATED_DATE
        FROM DEPOSIT_ITEM B
        JOIN INSTANT_PAYMENT E 
            ON B.EVENT_PAYMENT_ID = E.EVENT_PAYMENT_ID
        WHERE E.E_INVOICE_NBR = :E_INVOICE_NBR
        GROUP BY 
            B.EVENT_PAYMENT_ID, 
            E.PAYMENT_METHOD_ID
    ) COMBINED
    -- 按支付事件和支付方式分组
    GROUP BY EVENT_PAYMENT_ID, PAYMENT_METHOD_ID
) T
JOIN PAYMENT_METHOD PM 
    ON T.PAYMENT_METHOD_ID = PM.PAYMENT_METHOD_ID
	WHERE PM.PAYMENT_METHOD_CODE='25'
ORDER BY T.CREATED_DATE

-- ===== 10564 SALE_INVOICE_CHARGE_DETAILS_INFO_REVERSE =====
SELECT 
    T.CUST_ORDER_ID,
    T.ACC_NBR,
    T.ACCT_ID,
    T.CHARGE,
    T.FEE_ITEM,
    T.PAYMENT_TIME,
    T.PAYMENT_DATE,
    T.TAX_CHARGE,
    T.ROUNDING_AMOUNT,
    T.TAX_RATE,
    T.OFFER_NAME,
    CASE 
        WHEN T.GOODS_ORDER_ID IS NOT NULL AND 
             T.CHARGE = MAX(T.CHARGE) OVER (PARTITION BY T.CUST_ORDER_ID, T.ACC_NBR, T.GOODS_ORDER_ID) 
        THEN T.MODEL_NAME
        ELSE NULL
    END AS MODEL_NAME,
    T.GOODS_ORDER_ID
FROM 
    (SELECT 
        B.CUST_ORDER_ID,
        B.ACC_NBR,
        B.ACCT_ID,
        B.CHARGE AS CHARGE,
        B.FEE_ITEM,
        B.PAYMENT_TIME,
        B.PAYMENT_DATE,
        T.CHARGE AS TAX_CHARGE,
        CASE WHEN ROW_NUMBER() OVER (PARTITION BY B.CUST_ORDER_ID ORDER BY B.DEDUCT_SEQ) = 1 
             THEN NVL(R.ROUNDING_AMOUNT, 0) 
             ELSE 0 
        END AS ROUNDING_AMOUNT,
        B.TAX_RATE,
        B.OFFER_NAME,
        M.GOODS_ORDER_ID,
        CASE 
            WHEN M.MODEL_NAME IS NOT NULL 
            THEN M.MODEL_NAME
            ELSE NULL
        END AS MODEL_NAME
    FROM (
        -- Main fee records
        SELECT 
            D.CUST_ORDER_ID,
            B.DEDUCT_SEQ,
            B.PRICE_ID,
            D.ACC_NBR,
            D.ACCT_ID,
            B.CHARGE,
            F.ACCT_ITEM_TYPE_NAME AS FEE_ITEM,
            TO_CHAR(B.State_Date, 'HH:MIam') AS PAYMENT_TIME,
            TO_CHAR(B.State_Date, 'DD-Mon-YYYY') AS PAYMENT_DATE,
            G.TAX_RATE,
            AG.AGREEMENT_SHORT_NAME AS OFFER_NAME,
            F.ACCT_ITEM_TYPE_ID,
            F.ACCT_ITEM_TYPE_CODE,
            EP.EVENT_PAYMENT_ID
        FROM  EVENT_CHARGE B, RE_SUBS_ORDER_INST C, CRM.ORDER_ITEM D, ACCT_ITEM_TYPE F, EVENT_CHARGE_EXT H, GST_TYPE_TAX_RATE G, OFFER J, GST_TYPE K,CRM.AGREEMENT_ORDER M,AGREEMENT AG,
        EVENT_PAYMENT EP,EVENT_CHARGE Z
        WHERE 
         B.EVENT_INST_ID = C.EVENT_INST_ID
        AND D.ORDER_ITEM_ID = C.ORDER_ITEM_ID
        AND B.EVENT_INST_ID=Z.REVERSED_INST_iD
        AND Z.REVERSE_E_INVOICE_NBR = :E_INVOICE_NBR
        AND Z.PRICE_ID=B.PRICE_ID
        AND Z.ACCT_ITEM_TYPE_ID=B.ACCT_ITEM_TYPE_ID
        AND F.ACCT_ITEM_TYPE_ID = B.ACCT_ITEM_TYPE_ID
        AND B.BILLING_CYCLE_ID IS NOT NULL
        AND H.EVENT_INST_ID = B.EVENT_INST_ID
        AND H.PRICE_ID = B.PRICE_ID
        AND D.SUBS_PLAN_ID = J.OFFER_iD
        AND C.CUST_ORDER_ID = D.CUST_ORDER_ID
        AND H.SEQ = B.SEQ
        AND F.GST_TYPE = K.GST_TYPE
        AND F.GST_TYPE <> 'Z'
        AND H.DEDUCT_SEQ = B.DEDUCT_SEQ
        AND H.IS_TAX IS NULL
        AND F.GST_TYPE = G.GST_TYPE
        AND D.ORDER_ITEM_ID=M.ORDER_ITEM_ID
        AND M.AGREEMENT_ID = AG.AGREEMENT_ID
        AND C.EVENT_PAYMENT_ID=EP.EVENT_PAYMENT_ID
        AND D.SUBS_EVENT_ID=1
    ) B
    -- Tax records
    LEFT JOIN (
        SELECT 
            D.CUST_ORDER_ID,
            B.DEDUCT_SEQ,
            B.PRICE_ID,
            B.CHARGE,
            D.ACC_NBR
        FROM EVENT_CHARGE B, RE_SUBS_ORDER_INST C, CRM.ORDER_ITEM D, EVENT_CHARGE_EXT H,EVENT_PAYMENT EP,EVENT_CHARGE Z
        WHERE  B.EVENT_INST_ID = C.EVENT_INST_ID
        AND D.ORDER_ITEM_ID = C.ORDER_ITEM_ID
         AND B.EVENT_INST_ID=Z.REVERSED_INST_iD
        AND Z.REVERSE_E_INVOICE_NBR = :E_INVOICE_NBR
        AND Z.PRICE_ID=B.PRICE_ID
        AND Z.ACCT_ITEM_TYPE_ID=B.ACCT_ITEM_TYPE_ID
        AND B.BILLING_CYCLE_ID IS NOT NULL
        AND H.EVENT_INST_ID = B.EVENT_INST_ID
        AND H.PRICE_ID = B.PRICE_ID
        AND H.SEQ = B.SEQ
        AND C.EVENT_PAYMENT_ID=EP.EVENT_PAYMENT_ID
        AND C.CUST_ORDER_ID = D.CUST_ORDER_ID
        AND H.DEDUCT_SEQ = B.DEDUCT_SEQ
        AND H.IS_TAX = 'Y'
        AND D.SUBS_EVENT_ID=1
    ) T ON T.PRICE_ID = B.PRICE_ID 
        AND T.DEDUCT_SEQ <> B.DEDUCT_SEQ 
        AND T.ACC_NBR = B.ACC_NBR
        AND T.CUST_ORDER_ID = B.CUST_ORDER_ID
    -- Rounding amount
    LEFT JOIN (
        SELECT 
    D.CUST_ORDER_ID,
    MAX(B.CHARGE) AS ROUNDING_AMOUNT  -- or another aggregate function
FROM  EVENT_CHARGE B, RE_SUBS_ORDER_INST C, CRM.ORDER_ITEM D, ACCT_ITEM_TYPE F,EVENT_CHARGE Z
WHERE  B.EVENT_INST_ID = C.EVENT_INST_ID
AND D.ORDER_ITEM_ID = C.ORDER_ITEM_ID
AND C.CUST_ORDER_ID = D.CUST_ORDER_ID
AND B.EVENT_INST_ID=Z.REVERSED_INST_iD
AND Z.PRICE_ID=B.PRICE_ID
AND Z.ACCT_ITEM_TYPE_ID=B.ACCT_ITEM_TYPE_ID
AND Z.REVERSE_E_INVOICE_NBR = :E_INVOICE_NBR
AND D.SUBS_EVENT_ID=1
AND F.ACCT_ITEM_TYPE_ID = B.ACCT_ITEM_TYPE_ID
AND B.BILLING_CYCLE_ID IS NOT NULL
AND F.ACCT_ITEM_TYPE_CODE IN ('ROUNDING')
GROUP BY D.CUST_ORDER_ID
    ) R ON R.CUST_ORDER_ID = B.CUST_ORDER_ID
    LEFT JOIN (
    ---- GOODS Info
    SELECT  
     DISTINCT 
        D.CUST_ORDER_ID,
        E.GOODS_ORDER_ID,
        D.ACC_NBR,
        CASE 
            WHEN I.VALUE IS NOT NULL 
            THEN H.MODEL_NAME || ',' || I.VALUE  
            ELSE H.MODEL_NAME                  
        END AS MODEL_NAME
    FROM 
         EVENT_CHARGE B
        JOIN RE_SUBS_ORDER_INST C ON C.EVENT_INST_ID = B.EVENT_INST_ID
        JOIN EVENT_CHARGE Z ON  B.EVENT_INST_ID=Z.REVERSED_INST_iD AND Z.PRICE_ID=B.PRICE_ID AND Z.ACCT_ITEM_TYPE_ID=B.ACCT_ITEM_TYPE_ID
        JOIN CRM.ORDER_ITEM D ON D.ORDER_ITEM_ID = C.ORDER_ITEM_ID AND D.CUST_ORDER_ID = C.CUST_ORDER_ID
        JOIN ACCT_ITEM_TYPE F ON F.ACCT_ITEM_TYPE_ID = B.ACCT_ITEM_TYPE_ID
        JOIN CRM.GOODS_ORDER E ON D.ORDER_ITEM_ID = E.ORDER_ITEM_ID
        JOIN CRM.GM_MODEL H ON H.MODEL_ID = E.MODEL_ID
        JOIN CRM.GM_BRAND BR ON H.BRAND_ID=BR.BRAND_ID 
        AND BR.BRAND_CODE<>'Others'
        JOIN CRM.AGREEMENT_ORDER M ON D.ORDER_ITEM_ID = M.ORDER_ITEM_ID
        JOIN AGREEMENT AG ON M.AGREEMENT_ID = AG.AGREEMENT_ID
        AND AG.AGREEMENT_TYPE_ID='4'
        LEFT JOIN CRM.GOODS_ORDER_ATTR I ON E.GOODS_ORDER_ID = I.GOODS_ORDER_ID 
        AND I.ATTR_ID = 2725 
    WHERE 
        B.BILLING_CYCLE_ID IS NOT NULL
        AND Z.REVERSE_E_INVOICE_NBR = :E_INVOICE_NBR

        AND D.SUBS_EVENT_ID = 1
    ) M ON M.CUST_ORDER_ID = B.CUST_ORDER_ID
    AND M.ACC_NBR=B.ACC_nBR 

    UNION
    --tax
    SELECT 
        P.CUST_ORDER_ID,
        P.ACC_NBR,
        P.ACCT_ID,
        P.CHARGE AS CHARGE,
        P.FEE_ITEM,
        P.PAYMENT_TIME,
        P.PAYMENT_DATE,
        P.TAX_CHARGE AS TAX_CHARGE,
        P.ROUNDING_AMOUNT,
        P.TAX_RATE,
        P.OFFER_NAME,
        M.GOODS_ORDER_ID,
        CASE 
            WHEN M.MODEL_NAME IS NOT NULL 
            THEN M.MODEL_NAME
            ELSE NULL
        END AS MODEL_NAME

from


    ( SELECT 
        D.CUST_ORDER_ID,
        D.ACC_NBR,
        D.ACCT_ID,
        B.CHARGE AS CHARGE,
        F.ACCT_ITEM_TYPE_NAME AS FEE_ITEM,
        TO_CHAR(B.State_Date, 'HH:MIam') AS PAYMENT_TIME,
        TO_CHAR(B.State_Date, 'DD-Mon-YYYY') AS PAYMENT_DATE,
        0 AS TAX_CHARGE,
        0 AS ROUNDING_AMOUNT,
        J.TAX_RATE,
        AG.AGREEMENT_SHORT_NAME AS OFFER_NAME
    FROM  EVENT_CHARGE B, RE_SUBS_ORDER_INST C, CRM.ORDER_ITEM D, ACCT_ITEM_TYPE F,GST_TYPE H,GST_TYPE_TAX_RATE J,OFFER K,CRM.AGREEMENT_ORDER M,AGREEMENT AG,EVENT_CHARGE Z
    WHERE  B.EVENT_INST_ID = C.EVENT_INST_ID
    AND D.ORDER_ITEM_ID = C.ORDER_ITEM_ID
    AND F.GST_TYPE = H.GST_TYPE
    AND B.EVENT_INST_ID=Z.REVERSED_INST_iD
    AND Z.PRICE_ID=B.PRICE_ID
    AND Z.ACCT_ITEM_TYPE_ID=B.ACCT_ITEM_TYPE_ID
    AND D.SUBS_PLAN_ID=K.OFFER_ID
    AND D.SUBS_EVENT_ID=1
    AND D.CUST_ORDER_ID = C.CUST_ORDER_ID
    AND F.ACCT_ITEM_TYPE_ID = B.ACCT_ITEM_TYPE_ID
    AND B.BILLING_CYCLE_ID IS NOT NULL
    AND Z.REVERSE_E_INVOICE_NBR = :E_INVOICE_NBR
    AND H.GST_TYPE = 'Z'
    AND D.ORDER_ITEM_ID=M.ORDER_ITEM_ID
    AND M.AGREEMENT_ID = AG.AGREEMENT_ID
    AND H.GST_TYPE=J.GST_TYPE
    AND F.ACCT_ITEM_TYPE_CODE not in ('ZRL','ROUNDING')
    ) P
    LEFT JOIN (
    ---- GOODS Info
    SELECT  
     DISTINCT 
        D.CUST_ORDER_ID,
        E.GOODS_ORDER_ID,
        D.ACC_NBR,
        CASE 
            WHEN I.VALUE IS NOT NULL 
            THEN H.MODEL_NAME || ',' || I.VALUE  
            ELSE H.MODEL_NAME                  
        END AS MODEL_NAME
    FROM 
         EVENT_CHARGE B
        JOIN RE_SUBS_ORDER_INST C ON B.EVENT_INST_ID = C.EVENT_INST_ID
        JOIN EVENT_CHARGE Z ON  B.EVENT_INST_ID=Z.REVERSED_INST_iD AND Z.PRICE_ID=B.PRICE_ID AND Z.ACCT_ITEM_TYPE_ID=B.ACCT_ITEM_TYPE_ID

        JOIN CRM.ORDER_ITEM D ON D.ORDER_ITEM_ID = C.ORDER_ITEM_ID AND D.CUST_ORDER_ID = C.CUST_ORDER_ID
        JOIN ACCT_ITEM_TYPE F ON F.ACCT_ITEM_TYPE_ID = B.ACCT_ITEM_TYPE_ID
        JOIN CRM.GOODS_ORDER E ON D.ORDER_ITEM_ID = E.ORDER_ITEM_ID
        JOIN CRM.GM_MODEL H ON H.MODEL_ID = E.MODEL_ID
        JOIN CRM.GM_BRAND BR ON H.BRAND_ID=BR.BRAND_ID 
        JOIN CRM.AGREEMENT_ORDER M ON D.ORDER_ITEM_ID = M.ORDER_ITEM_ID
        JOIN AGREEMENT AG ON M.AGREEMENT_ID = AG.AGREEMENT_ID
        AND AG.AGREEMENT_TYPE_ID='4'
        AND BR.BRAND_CODE<>'Others'
        LEFT JOIN CRM.GOODS_ORDER_ATTR I ON E.GOODS_ORDER_ID = I.GOODS_ORDER_ID 
        AND I.ATTR_ID = 2725 
    WHERE 
        B.BILLING_CYCLE_ID IS NOT NULL
        AND D.SUBS_EVENT_ID = 1
    ) M ON M.CUST_ORDER_ID = P.CUST_ORDER_ID
    AND M.ACC_NBR=P.ACC_nBR
    
    UNION
      SELECT 
        D.CUST_ORDER_ID,
        D.ACC_NBR,
        D.ACCT_ID,
        A.CHARGE,
        E.ACCT_ITEM_TYPE_NAME AS FEE_ITEM,
        TO_CHAR(A.State_Date, 'HH:MIam') AS PAYMENT_TIME,
        TO_CHAR(A.State_Date, 'DD-Mon-YYYY') AS PAYMENT_DATE,
        0 AS TAX_CHARGE,
        0 AS ROUNDING_AMOUNT,
        0 AS TAX_RATE,
        AG.AGREEMENT_SHORT_NAME AS OFFER_NAME,
        NULL AS MODEL_NAME,  
        NULL AS GOODS_ORDER_ID
    FROM deposit_charge A
    JOIN RE_SUBS_ORDER_INST B ON A.event_inst_id = B.event_inst_id
    JOIN event_payment C ON B.event_payment_Id = C.event_payment_Id
    JOIN CRM.ORDER_ITEM D ON B.ORDER_ITEM_ID = D.ORDER_ITEM_ID
    JOIN ACCT_ITEM_TYPE E ON A.ACCT_ITEM_TYPE_ID = E.ACCT_ITEM_TYPE_ID
    JOIN CRM.AGREEMENT_ORDER M ON D.ORDER_ITEM_ID = M.ORDER_ITEM_ID
    JOIN AGREEMENT AG ON M.AGREEMENT_ID = AG.AGREEMENT_ID
    JOIN INSTANT_PAYMENT P ON P.EVENT_PAYMENT_ID=B.EVENT_PAYMENT_ID
    JOIN INSTANT_PAYMENT IP ON IP.REVERSED_PAYMENT_ID=P.PAYMENT_ID
    WHERE  IP.REVERSE_E_INVOICE_NBR = :E_INVOICE_NBR
    AND A.CHARGE>0
      AND D.SUBS_EVENT_ID = 1
    
     )T
   ORDER BY T.CUST_ORDER_ID, T.ACC_NBR, T.CHARGE

